#!/bin/sh
set -e
if [ "$1" = remove ] || [ "$1" = purge ]; then
    if [ -L /usr/bin/cm2 ] && [ "$(readlink /usr/bin/cm2)" = /opt/cm2/cm2 ]; then
        rm -f /usr/bin/cm2
    fi
fi
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
    db_purge
fi
